pipeline {
    agent any
    
    environment {
        // Specify the Maven installation name configured in Jenkins
        MAVEN_HOME = tool 'maven 3.9.6'
        BUILD_ID = "/"

    }
    stages {    
        stage('Build') {
            steps {
                script {
                    // Use 'sh' step with the full path to Maven executable
                    sh "${env.MAVEN_HOME}/bin/mvn clean package"
            }
                }
            }
        stage('Build docker Image')
        {
            steps
            {
                script
                {   
                  docker.withRegistry('https://index.docker.io/v1/', 'Docker') {
                def dockerImage = docker.build("selvapriya14/java_app:${env.BUILD_ID}", "-f var/lib/jenkins/workspace/New Java Project/jenkins/Dockerfile .")
                dockerImage.push()
                  }
                }
            }
        }
       stage('Run Docker Container') {
    steps {
        script {
            docker.image("selvapriya14/java_app:${env.BUILD_ID}").pull()
            // def BUILD_ID = env.BUILD_ID
            // echo "${BUILD_ID}"
            sh 'docker run -p 8181:8181 selvapriya14/java_app:$BUILD_ID'
          //def dockerContainer = docker.image("selvapriya14/java_app:${env.BUILD_ID}").run('-p 8181:8181')
 
           
        }
    }
       
       }
    }
}





