pipeline {
    agent any
    
    environment {
        // Specify the Maven installation name configured in Jenkins
        MAVEN_HOME = tool 'maven 3.9.6'
       

    }
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/selvapriya-s14/simple-java-maven-app.git'
            }
        }
        
        stage('Build') {
            steps {
                script {
                    // Use 'sh' step with the full path to Maven executable
                    sh "${env.MAVEN_HOME}/bin/mvn clean package"
                    docker.withRegistry('https://hub.docker.com/', 'Docker') {
                def dockerImage = docker.build("your-docker-image-name:${env.BUILD_ID}")
                dockerImage.push()

            }
                }
            }
        }
        
    }
}




