pipeline {
    agent any
    
    environment {
        // Specify the Maven installation name configured in Jenkins
        MAVEN_HOME = tool 'maven 3.9.6'
       

    }
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/selvapriya-s14/simple-java-maven-app.git'
            }
        }
        
        stage('Build') {
            steps {
                script {
                    // Use 'sh' step with the full path to Maven executable
                    sh "${env.MAVEN_HOME}/bin/mvn clean package"
            }
                }
            }
        stage('Build docker Image')
        {
            steps
            {
                script
                {
                    writeFile file: 'Dockerfile', text: '''
                FROM openjdk:11-jre-slim
                WORKDIR /app
                COPY target/*.jar app.jar
                EXPOSE 9999
                CMD ["java", "-jar", "app.jar"]
            '''
                  docker.withRegistry('https://index.docker.io/v1/', 'Docker') {
                def dockerImage = docker.build("docker_image:${env.BUILD_ID}")
                dockerImage.push()
                  }
                }
            }
        }
        
    }
}




